name: Build Linux

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: cmake
      run: |
        sudo apt install -y ninja-build
    - name: cmake
      run: |
        mkdir build
        cd build 
        cmake .. -G"Ninja"
        cmake --build .  --config RelWithDebInfo 
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        path: faceless
        directory: build
        filename: 'faceless-linux.zip'
    - uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: latest-linux
        prerelease: true
        title: Faceless Linux
        files: |
          build/faceless-linux.zip
