name: Build Windows

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: |
        mkdir build
        cd build
        cmake .. -GNinja
        ninja all
    - name: Easy Zip Files
      uses: vimtor/action-zip@v1
      with:
        files: build/bin/
        recursive: false
        dest: faceless.zip
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: latest-windows
        prerelease: true
        title: Faceless windows
        files: |
          faceless.zip
