name: Build Windows

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: cmake
      run: |
        mkdir build
        cd build 
        cmake .. -G"Visual Studio 16 2019"
        cmake --build . --config RelWithDebInfo 
    - name: Easy Zip Files
      uses: vimtor/action-zip@v1
      with:
        files: build/faceless
        recursive: false
        dest: faceless.zip
    - uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: latest-windows
        prerelease: true
        title: Faceless Windows
        files: |
          faceless.zip
